format_version: 4
pipelines:
  'prm-deductions-system-e2e.dev':
    group: deductions
    label_template: '${git[:8]}'
    timer:
      spec: "0 0 9,13,17,21 * * ?"
      only_on_changes: no
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      repo-to-gp:
        pipeline: prm-deductions-repo-to-gp.dev
        stage: deploy
      gp2gp-worker:
        pipeline: prm-deductions-gp2gp-worker.dev
        stage: deploy
      gp2gp-adaptor:
        pipeline: prm-deductions-gp2gp-adaptor.dev
        stage: deploy
      ehr-repo:
        pipeline: prm-deductions-ehr-repository.dev
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - test:
          clean_workspace: true
          jobs:
            test_lint:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_lint
            test_e2e:
              timeout: 15
              resources:
                - deductions-private
                - dev
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_e2e_test_harness
  'prm-deductions-system-e2e.test':
    group: deductions
    label_template: '${git[:8]}'
    timer:
      spec: "0 0 9,13,17,21 * * ?"
      only_on_changes: no
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      repo-to-gp:
        pipeline: prm-deductions-repo-to-gp.test
        stage: deploy
      gp2gp-worker:
        pipeline: prm-deductions-gp2gp-worker.test
        stage: deploy
      gp2gp-adaptor:
        pipeline: prm-deductions-gp2gp-adaptor.test
        stage: deploy
      ehr-repo:
        pipeline: prm-deductions-ehr-repository.test
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - test:
          clean_workspace: true
          jobs:
            test_lint:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_lint
            test_e2e:
              timeout: 15
              resources:
                - deductions-private
                - test
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_e2e
